version: '3.8'

services:
  documind-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: documind_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
    restart: unless-stopped
    networks:
      - documind_network

networks:
  documind_network:
    driver: bridge